-- 1.DISPLAY ALL TEAMS
SELECT * FROM TEAMS;

-- 2.DISPLAY ALL PLAYERS
SELECT * FROM PLAYERS;

-- 3.DISPLAY ALL MATCHES
SELECT * FROM MATCHES;

-- 4.DISPLAY PLAYER STATISTICS
SELECT * FROM PLAYER_STATISTICS;

-- 5.COUNT TOTAL TEAMS
SELECT COUNT(TEAM_ID) AS TOTAL_TEAMS FROM TEAMS;

-- 6.COUNT TOTAL PLAYERS
SELECT COUNT(PLAYER_NAME) AS TOTAL_PLAYERS FROM PLAYERS;

-- 7.DISPLAY NUMBER OF TOTAL MATCHES
SELECT COUNT(MATCH_ID) AS TOTAL_MATCHES_PLAYED FROM MATCHES;

-- 8.DISPLAY PLAYERS WITH THEIR TEAM NAME
SELECT PLAYER_NAME,TEAM_NAME
FROM PLAYERS AS P
JOIN TEAMS AS T
ON P.TEAM_ID=T.TEAM_ID;

-- 9.DISPLAY MATCH DETAILS WITH WINNER TEAM
SELECT MATCH_ID, TEAM_NAME AS WINNER_TEAM
FROM MATCHES AS M
JOIN TEAMS AS T
ON M.WINNER_TEAM_ID=T.TEAM_ID
ORDER BY MATCH_ID;

-- 10.DISPLAY MATCH BETWEEN TWO TEAMS AND THE WINNER
SELECT VENUE,MATCH_ID,T1.TEAM_NAME AS TEAM1,T2.TEAM_NAME AS TEAM2,T3.TEAM_NAME AS WINNER
FROM MATCHES AS M
JOIN TEAMS AS T1 ON M.TEAM1_ID=T1.TEAM_ID
JOIN TEAMS AS T2 ON M.TEAM2_ID=T2.TEAM_ID
JOIN TEAMS AS T3 ON M.WINNER_TEAM_ID=T3.TEAM_ID
ORDER BY MATCH_ID;
-- OR
-- 10.DISPLAY MATCH BETWEEN TWO TEAMS AND THE WINNER
SELECT VENUE,MATCH_ID,TEAM1_ID,TEAM2_ID,WINNER_TEAM_ID
FROM MATCHES AS M
JOIN TEAMS AS T
ON M.WINNER_TEAM_ID=T.TEAM_ID
ORDER BY MATCH_ID;

-- 11.DISPLAY THE NAMES OF PLAYERS OF EACH TEAM
SELECT PLAYER_ID,PLAYER_NAME,TEAM_NAME
FROM PLAYERS AS P
JOIN TEAMS AS T
ON P.TEAM_ID=T.TEAM_ID
ORDER BY PLAYER_ID;

-- 12.DISPLAY THE NUMBER OF MATCHES PLAYED BY EACH TEAM
SELECT TEAM_ID,COUNT(*) AS MATCHES_PLAYED
FROM (SELECT TEAM1_ID AS TEAM_ID FROM MATCHES
UNION ALL
SELECT TEAM2_ID FROM MATCHES) AS ALL_MATCHES
GROUP BY TEAM_ID;

-- 13.DISPLAY THE NUMBERS OF WINS PER TEAM
SELECT T.TEAM_ID,T.TEAM_NAME,COUNT(WINNER_TEAM_ID) AS MATCHES_WON
FROM MATCHES AS M
JOIN TEAMS AS T
ON M.WINNER_TEAM_ID=T.TEAM_ID
GROUP BY TEAM_ID
ORDER BY MATCHES_WON DESC;

-- 14.DISPLAY PLAYER NAME WITH THEIR TEAM
SELECT PLAYER_NAME,TEAM_NAME
FROM PLAYERS AS P
JOIN TEAMS AS T
ON P.TEAM_ID=T.TEAM_ID;

-- 15.DISPLAY TOTAL RUNS AND TOTAL WICKETS PER PLAYER
SELECT P.PLAYER_NAME,P_S.PLAYER_ID,SUM(RUNS) AS TOTAL_RUN,SUM(WICKETS) AS TOTAL_WICKETS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.PLAYER_ID=P_S.PLAYER_ID
GROUP BY PLAYER_ID;

-- 16.DISPLAY THE NAME OF HIGHEST RUN SCORER (ORANGE CAP)
SELECT P.PLAYER_NAME AS HIGHEST_RUN_SCORER, SUM(RUNS) AS TOTAL_RUN
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.PLAYER_ID=P_S.PLAYER_ID
GROUP BY PLAYER_NAME
ORDER BY TOTAL_RUN DESC
LIMIT 1;

-- 17.DISPLAY THE NAME OF HIGHEST WICKET TAKER (PURPLE CAP)
SELECT P.PLAYER_NAME AS HIGHEST_WICKET_TAKER, P.PLAYER_ID, SUM(WICKETS) AS TOTAL_WICKETS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.PLAYER_ID=P_S.PLAYER_ID
GROUP BY PLAYER_ID
ORDER BY TOTAL_WICKETS DESC
LIMIT 1;

-- 18.DISPLAY AVERAGE RUNS PER MATCH PER PLAYER
SELECT PLAYER_ID,AVG(RUNS) AS AVG_RUNS
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID;

-- 19.DISPLAY THE TOTAL RUNS SCORED IN ALL MATCHES
SELECT SUM(RUNS) AS TOTAL_RUNS FROM PLAYER_STATISTICS;

-- 20.DISPLAY THE NAME OF THE SECOND HIGHEST RUN SCORER
SELECT P.PLAYER_NAME,P.TEAM_ID,P.PLAYER_ID,SUM(RUNS) AS TOTAL_RUNS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.TEAM_ID=P_S.PLAYER_ID
GROUP BY PLAYER_ID
ORDER BY TOTAL_RUNS
LIMIT 1 OFFSET 1;

-- 21.DISPLAY THE NAME OF SECOND HIGHEST WICKET TAKER
SELECT P.PLAYER_ID, P.PLAYER_NAME,SUM(WICKETS) AS TOTAL_WICKETS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.PLAYER_ID=P_S.PLAYER_ID
GROUP BY PLAYER_ID
ORDER BY SUM(WICKETS) DESC
LIMIT 1 OFFSET 1;

-- 22.DISPLAY THE NAME OF PLAYERS WHO SCORED MORE THAN 50 IN ANY MATCH
SELECT DISTINCT P_S.PLAYER_ID,P_S.RUNS,P.PLAYER_NAME
FROM PLAYER_STATISTICS AS P_S
JOIN PLAYERS AS P
ON P_S.PLAYER_ID=P.PLAYER_ID
WHERE RUNS>50
ORDER BY PLAYER_ID;

-- 23.RANK ALL THE PLAYERS BY TOTAL RUNS
SELECT PLAYER_ID, SUM(RUNS), DENSE_RANK() OVER(ORDER BY SUM(RUNS) DESC) AS PLAYER_RANK
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID;

-- 24.RANK ALL THE PLAYERS BY TOTAL WICKETS
SELECT PLAYER_ID,SUM(WICKETS),DENSE_RANK() OVER(ORDER BY SUM(WICKETS) DESC) AS PLAYER_RANK
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID;

-- 25.ROW NUMBER RANKING OF PLAYERS BY RUNS
SELECT PLAYER_ID,SUM(RUNS), ROW_NUMBER() OVER(ORDER BY SUM(RUNS) DESC) AS ROW_NUMBERS
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID;

-- 26.TOP THREE PLAYERS PER RANKING
SELECT PLAYER_ID, SUM(RUNS), DENSE_RANK() OVER(ORDER BY SUM(RUNS) DESC) AS PLAYER_RANK
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID
LIMIT 3;

-- 27.RANK THE PLAYERS BY COMBINED PERFORMANCE
SELECT PLAYER_ID, SUM(RUNS+WICKETS) AS SCORE,
DENSE_RANK() OVER(ORDER BY SUM(RUNS+WICKETS) DESC) AS PERFORMANCE_RANK
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID;

-- 28.DISPLAY THE MAN OF THE TOURNAMENT
SELECT PLAYER_ID, SUM(RUNS+WICKETS) AS SCORE,
DENSE_RANK() OVER(ORDER BY SUM(RUNS+WICKETS) DESC) AS PERFORMANCE_RANK
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID
LIMIT 1;

-- 29.DISPLAY THE NUMBER OF MATCHES PLAYED AT EACH VENUE
SELECT VENUE,COUNT(VENUE) AS MATCH_PLAYED
FROM MATCHES
GROUP BY VENUE;

-- 30.CTE FOR PLAYER TOTAL RUNS
WITH PLAYER_RUNS AS (SELECT P.PLAYER_NAME, P.PLAYER_ID, SUM(RUNS) AS TOTAL_RUNS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S
ON P.PLAYER_ID=P_S.PLAYER_ID
GROUP BY PLAYER_ID)
SELECT * FROM PLAYER_RUNS;

-- 31.PLAYERS WITH MORE THAN 200 RUNS USING CTE
WITH PLAYER_RUNS AS (SELECT PLAYER_ID, SUM(RUNS) AS TOTAL_RUNS
FROM PLAYER_STATISTICS
GROUP BY PLAYER_ID
HAVING SUM(RUNS)>200)
SELECT * FROM PLAYER_RUNS;

-- 32.TEAMS PERFORMANCE USING CTE
WITH TEAMS_PERFORMANCE AS (SELECT T.TEAM_NAME, COUNT(WINNER_TEAM_ID) AS WINS
FROM TEAMS AS T
JOIN MATCHES AS M
ON T.TEAM_ID=M.WINNER_TEAM_ID
GROUP BY WINNER_TEAM_ID)
SELECT * FROM TEAMS_PERFORMANCE;

-- 33.DISPLAY THE NAME OF THE WINNER TEAM
SELECT T.TEAM_NAME AS WINNER_TEAM,COUNT(WINNER_TEAM_ID) AS MATCHES_WON
FROM TEAMS AS T
JOIN MATCHES AS M
ON T.TEAM_ID=M.WINNER_TEAM_ID
GROUP BY TEAM_NAME
ORDER BY COUNT(WINNER_TEAM_ID) DESC
LIMIT 1;

-- 34.CREATE A VIEW FOR PLAYER PERFORMANCE
CREATE VIEW PLAYERS_PERFORMANCE AS
SELECT P.PLAYER_ID,T.TEAM_NAME, P.PLAYER_NAME, SUM(RUNS) AS TOTAL_RUNS, SUM(WICKETS) AS TOTAL_WICKETS
FROM PLAYERS AS P
JOIN PLAYER_STATISTICS AS P_S ON P.PLAYER_ID=P_S.PLAYER_ID
JOIN TEAMS AS T ON P.TEAM_ID=T.TEAM_ID
GROUP BY PLAYER_ID;
SELECT * FROM PLAYERS_PERFORMANCE
ORDER BY PLAYER_ID;

-- 35.CREATE A VIEW FOR TEAMS PERFORMANCE
CREATE VIEW TEAMS_PERFORMANCE AS
SELECT T.TEAM_ID,T.TEAM_NAME, COUNT(WINNER_TEAM_ID) AS MATCHES_WON
FROM TEAMS AS T
JOIN MATCHES AS M
ON T.TEAM_ID=M.WINNER_TEAM_ID
GROUP BY WINNER_TEAM_ID;

SELECT * FROM TEAMS_PERFORMANCE
ORDER BY MATCHES_WON DESC;
