CREATE DATABASE IPL_2026;
USE IPL_2026;

CREATE TABLE TEAMS(
TEAM_ID INT PRIMARY KEY,
TEAM_NAME VARCHAR(50));

CREATE TABLE PLAYERS(
PLAYER_ID INT PRIMARY KEY,
PLAYER_NAME VARCHAR(50),
TEAM_ID INT,
FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID));

CREATE TABLE MATCHES(
MATCH_ID INT PRIMARY KEY,
MATCH_DATE DATE,
TEAM1_ID INT,
TEAM2_ID INT,
WINNER_TEAM_ID INT,
VENUE VARCHAR(50),
FOREIGN KEY (TEAM1_ID) REFERENCES TEAMS(TEAM_ID),
FOREIGN KEY (TEAM2_ID) REFERENCES TEAMS(TEAM_ID),
FOREIGN KEY (WINNER_TEAM_ID) REFERENCES TEAMS(TEAM_ID));

CREATE TABLE PLAYER_STATISTICS(
STAT_ID INT PRIMARY KEY,
MATCH_ID INT,
PLAYER_ID INT,
RUNS INT,
WICKETS INT,
FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID));